version: '2'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    command: --character-set-server=utf8 --collation-server=utf8_czech_ci
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=mydb"
    ports:
      - "3306:3306"
    volumes:
      - ./db/baseData.sql:/docker-entrypoint-initdb.d/dump.sql

  counting_app:
    container_name: counting_app
    image: 'pia/cagy'
    ports:
      - '8081:8081'
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - "mariadb"
